### ISSUE TITLE
Adding in new maps

### ISSUE THREAD

**Issue by Ariston1204** [jweigelt/swbf2admin#31]
Hello,

I've been trying to figure out how to install a new map into the server but nothing seems to work.

**Comment by Legitosity** [comment]
Hello Ariston, 

Adding new maps is a fairly easy process. You need to create an /addon folder for the server just like you would on your own game. Once the maps are placed inside, you need to change the swbf2admin.sqlite file (I use DB Browser for SQLITE to do this) and navigate to the swbf_maps table creating a new row at the bottom. This is changing the webadmin database so that you can view your new map via the online interface. You can copy the format of the other maps (map name code, nice name etc,) however for the game modes, there is an html doc in the root of the folder (named something like gametype_flags.html) which you can use to calculate what game modes you'd like selected.

Hope this helps!

**Comment by Ariston1204** [comment]
Thanks!
