### ISSUE TITLE
Enabling !applymods commands

### ISSUE THREAD

**Issue by ForceFlowingYoda** [jweigelt/swbf2admin#34]
I downloaded the latest revision of SWBF2 ADMIN 1.2.8 with the updated xml file. 
I dragged the contents of the Gamedata Folder into (.server folder)
I enabled runtime, and the server starts on Webadmin.
When I type !applymods enable no_force on the web admin chat it says Admin: Applied no_force in game
then I have my user logged in through /admin /login password
I type  /admin /endgame to reset the game.
I also have tried just !endgame in Webadminchat
The No Force mod still not seeming to work. Force Push and Pull are still working.

I am confused by what you mean by (Simply copy the contents of _LVL_PC from the old server package to ./server/_LVL_PC ...) 
Take the _LVL_PC folder  from the GOG files, and copy the entire folder into the server folder? or the contents inside folder only?, Or The Opposite? What is old server package? (GOG)?

Also how you use !applymods inside of game,I don't know the exact phrase right after I hit the T button to type, I tried these. After being logged in through /admin /login password 
!applymods enable no_force
/admin !applymods enable no_force
/admin /applymods enable no_force
/admin /!applymods enable no_force

all said command not found
and how do I get !gimmeadmin to work inside of game?
what is the exact phrase I type, I also tried that command as the same format as above

I'm pretty new to this all, I'm trying to understand. And most of all to get the No Force Mod to work. I have looked at #32 . But I am not clear on what I am doing to get it to work.

**Comment by jweigelt** [comment]
The mods were designed to work on *textureless* data files and will likely not work on standard game files. Textureless files were included in the old server package that can be found through a bit of research:
(https://www.moddb.com/games/star-wars-battlefront-ii/downloads/star-wars-battlefront-ii-v11-dedicated-server)

(This means download and install the old package, and copy the contents of `<old package server dir>.../data/_lvl_pc` to `./server/data/_lvl_pc`. If done right, this should effectively overwrite the current .lvl files.)

Ingame commands do not require being logged in and have to be entered without `/admin` prefix.
(see https://github.com/jweigelt/swbf2admin#ingame-commands)

**Comment by ForceFlowingYoda** [comment]
Thank you, The server no force mod now works.

Still haven't got !gimmeadmin to work, but I'll look into that more.

**Comment by jweigelt** [comment]
!gimmeadmin works by just joining the server and typing `!gimmeadmin` in chat.

A few things to consider:
- !gimmeadmin is deactivated after one use (it is just intended to be quick way of gaining initial permissions)
- !gimmeadmin can only be run in-game and not via web chat
- Due to certain limitations in the game, there is a maximum length for player names when running commands. Not sure on the exact number, but it's somewhere around 20 characters.
- If you don't plan on using !gimmeadmin immediately, you should disable it by setting `Enabled` to false in `./cfg/cmd/gimmeadmin.xml` to prevent other players from running the command.

**Comment by ForceFlowingYoda** [comment]
Okay, I have been running a server with over 20 players.
I disabled it by putting the setting to false.

Also is it possible to add a Time Limit to Mos Eisley Assault (Heroes v Villans) at this time?
Time limit on ELI or ASS on the Webadmin do not work to put a time limit on that map and mode.

**Comment by jweigelt** [comment]
To my knowledge assault mode does not support setting a timer (at least the gameserver does not provide any setting for it...).
I am not that familiar with how gameplay as affected by various settings (also what their default values are), since this is all handled internally by the game and not the server manager. People who actively played the game more than I did may have better anwers on that.

My position on chat autokick is still the same as in #33.
